[package]
name = "block-printer"
version = "0.1.0"
edition = "2024"

[dependencies]
alloy = { version = "1", features = ["full"] }
clap = { version = "4.5.60", features = ["derive"] }
crossterm = "0.29.0"
dotenv = "0.15.0"
eyre = "0.6.12"
futures-util = "0.3.32"
ratatui = "0.30.0"
sqlx = { version = "0.8.6", features = ["runtime-tokio", "sqlite", "macros"]}
tokio = { version = "1", features = ["full"] }
tokio-stream = "0.1.18"

